services:
  postgres:
    container_name: postgres-sql-em
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: employee_app
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  ems-api:
    container_name: ems-api
    image: ems/ems:1.0.0
    ports:
      - 8083:8083
    networks:
      - spring-demo
    depends_on:
      - postgres

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
